name: Create rolling release

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'appveyor.yml'
      - 'scripts/*'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'appveyor.yml'
      - 'scripts/*'
  workflow_dispatch:

jobs:
  windows-build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0
        submodules: true

    - name: Compile release build
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        msbuild duckstation.sln -t:Build -p:Platform=x64;Configuration=ReleaseLTCG

    - name: Remove extra bloat before archiving
      shell: cmd
      run: |
        del /Q bin\x64\*.pdb
        del /Q bin\x64\*.exp
        del /Q bin\x64\*.lib
        del /Q bin\x64\*.iobj
        del /Q bin\x64\*.ipdb
        del /Q bin\x64\common-tests*
        del /Q bin\x64\duckstation-libretro-*
                
    - name: Create release archive
      shell: cmd
      run: |
        "C:\Program Files\7-Zip\7z.exe" a -r duckstation-windows-x64-release.7z ./bin/x64/*

    - name: Upload release artifact
      uses: actions/upload-artifact@v1
      with:
        name: "windows-x64"
        path: "duckstation-windows-x64-release.7z"

  create-release:
    needs: [windows-build]
    runs-on: "ubuntu-latest"
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download Windows x64 Artifact
        uses: actions/download-artifact@v1
        with:
          name: "windows-x64"

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Latest Development Build"
          files: |
            windows-x64/duckstation-windows-x64-release.7z

